    import Modal from "@/Components/Modal";
    import InputWrapper from "@/Components/InputWrapper";
    import PrimaryButton from "@/Components/PrimaryButton";
    import TextInputGroup from "@/Components/TextInputGroup";
    import { IoMdClose } from "react-icons/io";
    import { useEffect, useState } from "react";
    import { router, useForm } from "@inertiajs/react";
    import { fieldTitles, validFieldIds } from "./fieldTitles";
    interface Row {
        payroll_id: string | number;
        user_id: string | number;
        basic_pay?: number | string;
        pera?: number | string;
        [key: string]: any;
    }

    interface Props {
        show: boolean;
        onClose: () => void;
        row: Row;
    }

    export default function PayrollEditModal({ show, onClose, row}: Props) {
        const [submitTrigger, setSubmitTrigger] = useState<"partial" | "publish" | null>(null);
        console.log("row ni",row);
        const { data, setData, post } = useForm<any>({
            payroll_id: "",
            user_id: "",
            basic_salary: "",
            pera: "",
            absent: "",
            late: "",
            holding_tax: "",
            tax_bal_due: "",
            rlip: "",
            policy_loan: "",
            consol_loan: "",
            emerg_loan: "",
            gel: "",
            gfal: "",
            mpl: "",
            mpl_lite: "",
            contributions: "",
            loans: "",
            housing_loan: "",
            philhealth: "",
            cfi: "",
            tipid: "",
            city_savings_bank: "",
            fea: "",
            canteen: "",
            disallowance: "",
            unliquidated_ca: "",
            disallowance_honoraria: "",
            coop: "",
            landbank: "",
            ucpb: "",
            publish_status: "",
            deduction1:"",
            deduction2:"",
            deduction3:""
        });
        useEffect(() => {
            if (show && row?.payroll_id && row?.payslip_type) {
                router.get(
                    route("admin.payroll.edit.data", {
                        payroll_id: row.payroll_id,
                        payslip_type: row.payslip_type,
                    }),
                    {},
                    {
                        preserveState: true,  
                        preserveScroll: true,
                        only: ["editPayroll"], 
                        onSuccess: (page: any) => {
                            if (page.props?.editPayroll) {
                                setData((prev: any) => ({
                                    ...prev,
                                    ...page.props.editPayroll,
                                }));
                            }
                        },
                    }
                );
            }
        }, [show, row?.payroll_id, row?.payslip_type]);



        const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
            const { name, value } = e.target;
            if (validFieldIds.includes(name) && /^\d*\.?\d*$/.test(value)) setData(name, value);
        };

    // Publish / Partial
        const handleEdit = (actionType: "partial" | "publish") => (e: React.FormEvent) => {
            e.preventDefault();
            setData("publish_status", actionType);
            setSubmitTrigger(actionType);
        };

        useEffect(() => {
            if (submitTrigger && data.publish_status === submitTrigger) {
            post(route("admin.payroll.update-partial-publish", data.payroll_id), {
                onSuccess: () => {
                setSubmitTrigger(null);
                onClose();
                },
            });
            }
        }, [data.publish_status, submitTrigger]);

        const renderSectionFields = () => (
            fieldTitles.map((section, idx) => (
                <InputWrapper key={idx} className="p-3 text-white space-y-4">
                <p className="font-medium">{section.title}</p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-x-6 gap-y-4">
                    {section.fields.map(({ label, id, disabled = false }) => (
                    <TextInputGroup
                        key={id}
                        label={label}
                        id={id}
                        name={id}
                        value={data[id] ?? ""}
                        onChange={handleInputChange}
                        disabled={disabled}
                        placeholder={label === "RLIP" || label === "Philhealth" ? "(AUTOGENERATED)" : ""}
                    />
                    ))}
                </div>
                </InputWrapper>
            ))
        )
            
        const renderFooter = () => (
            <div className="flex gap-4">
                <PrimaryButton onClick={handleEdit("publish")} className="text-md mt-4 py-2 hover:bg-yellow-600">
                Publish
                </PrimaryButton>
                <PrimaryButton onClick={handleEdit("partial")} className="text-md mt-4 hover:bg-yellow-600">
                Partial
                </PrimaryButton>
                <PrimaryButton onClick={onClose} className="text-md mt-4 hover:bg-yellow-600">
                Cancel
                </PrimaryButton>
            </div>
        )
        if (!show) return null;

        return (
            <Modal show={show} onClose={onClose} maxWidth="5xl" className="h-full">
            <form>
                <div className="p-6 space-y-4 border rounded-lg">
                <div className="flex justify-between">
                    <h2 className="text-lg font-bold mb-4 text-white">
                    Edit Employee's Payroll
                    </h2>
                    <span onClick={onClose}>
                    <IoMdClose color="white" className="cursor-pointer text-2xl" />
                    </span>
                </div>

                <InputWrapper className="flex gap-4 p-3">
                    <TextInputGroup label="Basic Salary" id="basic_salary" name="basic_salary" value={data?.basic_salary} disabled />
                    {row?.payslip_type === "Part-Time" && (
                    <><TextInputGroup label="Hourly Rate" id="hourly_rate" name="hourly_rate" onChange={handleInputChange} />
                    <TextInputGroup name="units" label="Units" id="units" onChange={handleInputChange} />
                    <TextInputGroup name="duty_count" label="Duty Count" id="duty_count" onChange={handleInputChange} />
                    </>
                    )}
                    <TextInputGroup name="pera" label="PERA" id="PERA" value={data?.pera} onChange={handleInputChange} />
                    
                </InputWrapper>
                {renderSectionFields()}
                {renderFooter()}
                </div>
            </form>
            </Modal>
        );  
    }